[package]
name = "imu"
version = "0.1.0"
authors = ["Josh Mcguigan"]
edition = "2018"
build = "build.rs"

[dependencies]
libm = "0.1.2"

[dev-dependencies]
quickcheck = "0.8"
rand = "0.6"

[build-dependencies]
cc = "1.0.28"
